# ==============================
# 🔬 LCS ANALYSIS (Histogram + Boxplot)
# ==============================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ==============================
# ✏️ STEP 1: PASTE YOUR SEQUENCES
# ==============================

bricks_24 = [
    "CCACAATCTTGCGTTAGGTGGAACTCTTCCAGCTTCGGATAGGAAGCA",
        "TGACTAGAAGTCGTGTCGGCCATT",
        "AGTCATACTGTCGCCGGTGCAGTC",
        "AACTAGAACTTCGTCGTTGAGCGC",
        "AACAATTCTTGCGATTAGGCGGCC",
        "CAACAACTTGACGGAGTTGGCTTC",
        "TATGTATTACTCGTCACGGAATGC",
        "CTCTCAATTCTCGCATAAGACGTG",
        "ACCTCTATAGACGATGGTGAGCTC",
        "CACTCATATCACGTCAATGGCAGG",
        "GTAATACTCTTCGGTGGAGCCGAC",
        "CCACCAACAATCGTATTGTGGTCA",
        "CGCTTGCTTAACGGCAAGGCTAAT",
        "ACCTCTACTGTCGTAGAGGCAGAT",
        "CACACTCCATTCGAAGTGGAGGTT",
        "ATTATTCAAGGCGTCGAAGCCGCT",
        "CTACATACTTGCGTAGTAGCACGG",
        "CAATAACTCTCCGGTTAGGTGAGC",
        "CCATATTCCATCGCCGTGGAGTAG",
        "CCTCACAATTACGTTAGTGCATGA",
        "CTCTCGTGTAACGAAGGTGTCACA",
        "ACTTCCATTAGCGGTCGTGTCTAC",
        "ACATCCGATGTCGATGAGGTATCC",
        "ATCAATTAAGGCGACTGTTCCGCG",
        "CGCATTCGGACCGTAATGGTAATC",
        "CAAGAGTATTGCGCAGTTGCCTCA",
        "CACTAACTACACGTAGCTGTGGTG",
        "CTACAGACGTTCGAAGAGGTTCAC",
        "CCAATACCTGACGGACATCGCTAG",
        "AACTAAGTGGCCGTATCGGCATCT",
        "ACACCTATATCCGTTACGTCAACC",
        "CCTAATCTAAGCGGTATTGCAGCG",
        "TCCGTGATCAACGTTGTGGTTGGA",
        "CTTCTCTACTCCGGATGTGAGAAG",
        "CTCCATTGAGACGTGAATGCATCG",
        "CCGGAGCAACACGTATTGGTTACT",
        "CAGCAGAGTTCCGTATAGGTTCCA",
        "ACTAACTTATTCGATGCGGCCGAGCTCAAGACCTACGTGGAGGTCTAT",
]

bricks_20 = [
   "TATCCGAATCCTGGCGAAGG",
"GACTCGTCATCTGGCGGACA",
"TTAACGAAGGTTGACGCTTG",
"GTCACGGTATTGTGCGGTAT",
"TGCACGAATTGATCCGAGTG",
"GTTACGACACATGCCGTGTA",
"GTATCGAAGACAGACGAAGT",
"GAGACGTAATTAGGCGACAT",
"TGTACGATCATAAGCGCAGA",
"CAGCCGTAGGAATTCGCTTC",
"ACAACGGAGACCTGCGACAG",
"TATGCGAGTATAGTCGCTGA",
"ATATCGCTAACCAGCGCATG",
"TGTTCGTATGTGATCGCAGA",
"ACTGCGGAGTGAAGCGCTCA",
"AATGCGAAGGATCACGTTCT",
"GTGGCGGAGAGTTCCGTCTA",
"CCAGCGTTCATTGCCGCTAA",
"GAATCGTAAGGTACCGTCTG",
"ATAACGGACATTACCGTCCA",
"TCCACGCTAACTTACGTGCT",
"TAGGCGTATAGTTGCGGAAG",
"ACCACGATCATGGTCGGTAC",
"TAATCGAGACTGGCCGATAG",
"ATCACGATACTGCACGCACT",
"TCTTCGTTGACTAGCGGCTA",
"TGAACGTCTAGGTACGAGGT",
"TGTCCGCCTATACTCGGACT",
"AGTTCGTCATACTACGCTGA",
"TGCTCGACATATAACGTCCA",
"AGGCCGCTATGCAGCGGTAT",
"ATAACGTGTCACATCGACTT",
"CTAGCGACTCTGTACGAGCC",
"ACTGCGTGATACCACGATCT",
"TAGCCGATAACCTACGGAGC",
"GTCTCGTCCTTGTCCGAGGA",
"TTGCCGGTTGACTACGCCAA",
"CTAACGGCTTGGATCGTTAA",
"ACACCGCCTTAATGCGATTG",
"CTGACGATTGCTCTCGTACC",
"CACTCGACTATGGTCGATAT",
"CAGTCGGCTCTTGCCGCATT",
"GAAGCGCATACTTGCGCTCT",
"GGTCCGTAACATCTCGGATG",
"TCAACGTACTCATACGTCTG",
"TTACCGTGGCCTCTCGCCAT",
"CTGGCGTGATACTACGCCTG",
"AGTACGGCCTGATGCGTCTC",
"TAGCCGAATGGCCTCGTGAT",
"TCTCCGTCCATTAACGTATG",
"CAGCCGTTATTATGCGGATG",
"AGTTCGTGGTGAACCGTTGC",
"CACACGGTCATTCACGGTGT",
"ACAGCGCACCATGGCGGTTA",
"GCAGCGTTAGTCCTCGCTCT",
"TAATCGCAGCACCTCGATAG",
"GAAGCGGAACTAACCGCTGA",
"GGATCGACTGTACACGATGG",
"TCTACGAAGGAATTCGAGCT",
"CCAGCGATAGAACACGCTCC",
"AATGCGTCTCAAGGCGCAGA",
"TATCCGCCACTAGCCGGAAG",
"AGTACGGAATAATCCGGTAG",
"AACACGAGTTAGGTCGTCAT",
"AGGTCGAAGCTACTCGAATA",
"TTGACGCTGACCAACGTACC",
"ACAACGTAAGACTACGTAAC",
"ATATCGCATTGATGCGCTAA",
"CATGCGGAATGAACCGTAGC",
"AATACGTAGTGCACCGAGCC",
"TGTCCGGAGCTTCACGCTGA",
"ACTACGTACTATTCCGTGCA",
"GCTCCGAACTAGACCGATCT",
"CACACGCATGTTACCGCTGT",
"GATGCGGAATCTTCCGACCT",
"GACTCGAAGAATGTCGACAA",
"TAACCGACAGTAATCGGTAG",
"CTCTCGTCTAGTGACGGCAC",
"CTACCGATGTTGCTCGATAC",
"AGATCGATCTGCCTCGAAGA",
"CTATCGAGTGAACTCGCCTC",
"GGTACGCAAGGAAGCGTGAT",
"CAACCGTAATCCTACGAACT",
"GAAGCGTCTGCTAGCGCTTA",
"GCTTCGTATTCTAACGTCAG",
"CAATCGGTGGTTACCGTTCT",
"CAACCGCCTACTCTCGGTTG",
"AATTCGGAGATAGCCGGCCT",
"AGTGCGCAGGATGCCGCTAA",
"ATGTCGAAGGCATTCGTTGT",
"CCTACGCTACTCAGCGGAAC",
"GTTCCGGTAAGAGTCGTCTA",
"ACAGCGCAGTAATGCGAAGT",
"AGTTCGCCATTAGTCGAACC",
"GGTGCGATATTAATCGGCTT",
"GGTGCGAATGATTGCGCACA",
"CTCTCGAATGATATCGTCTA",
"GATCCGGTTGTAGCCGGTCT",
"CACACGGAGTTCACCGTGTC",
"GTAACGATAGATACCGTTGC",
"TGAGCGGCAGCTCACGGTTA",
"AGATCGGTATGGTCCGCAGA",
"TGAGCGGAAGGTTCCGGTAT",
"ATTGCGTACTCATCCGCATA",
"GCATCGAATAAGGTCGCTGA",
"CTAACGTTCACCAACGAGTC",
"TTGGCGCTTGATAGCGTAGG",
"GATCCGTGGTAGAACGGTTC",
"ATTACGTAGCAGAGCGTATA",
"TATACGAGGCTCCACGCCAG",
"GTTCCGGAGTTATCCGGTAG",
"AATTCGTCAATTAGCGTTGA",
"TTGACGACAACAATCGCCAC",
"TTACCGTATTACTTCGTGAC",
"TTGACGTGCCTTCACGCTCC",
"ATATCGAACACTGTCGTGAA",
"CATTCGTCATTGAACGAATC",
"GAGGCGGATGACTCCGTTAC",
"CTGCCGTGCACACACGTTCA",
"AGACCGTCTTATTGCGGTGA",
"GTTGCGCTGAGACACGCAAC",
"TACTCGTGTAGTACCGAGTG",
"GTCACGAGCTATCTCGGTGT",
"CAATCGAAGCATTACGCAAT",
"TGTCCGTTAACTCACGACAA",
"CAACCGATTACTATCGTAGT",
"ATAGCGGTCAAGGTCGCTCT",
"CTCACGCAATGAGCCGTGGT",
"AGAGCGAGAGTGCTCGAACC",
"GAGACGTAGGTGTACGACTA",
"GCATCGTCTCCTAACGCTAT",
"CCTACGAGTCAGTACGTGTG",
"CATTCGCCAGTTGGCGACTC",
"GTTCCGTGCTGCCACGTTAC",
"AGGTCGCTCTACAGCGCTCT",
"GACACGGTATGCACCGTCCA",
"CAGACGTATAGACACGTCAA",
"TGGACGAGTTGTGCCGTATG",
"GATGCGTAGCAATACGATAC",
"CATACGTAAGTCTACGGTGA",
"GGTTCGCTTAATAGCGGAAG",
"TTACCGTGTGAATCCGGTCT",
"ACTGCGCCATTGGCCGAATT",
"GCTCCGATCTGAATCGACCT",
"AGTACGGTTGTGACCGGACA",
"GATCCGTTACCATTCGTAAC",
"TGTGCGAGAATCTGCGCATA",
"GTTGCGCTATGGAGCGAGTA",
"ACTCCGCTCACTAGCGATAT",
"GGCACGAGTAGTGTCGAATC",
"GGATCGCACAGATGCGTGGT",
"TTCTCGAGTCTTCTCGTATA",
"CAGTCGAGTCTCTACGGAAC",
"CCATCGCCAACAGGCGATTG",
"AGGTCGGCTGTAGCCGATTA",
"AGCACGTGGAACTTCGGTGC",
"CAGCCGTCTTATACCGGCAC",
"AAGGCGCTCCTCACCGATAT",
"ATTGCGCCAAGTAGCGCATA",
"CTCACGGTTGCCACCGTTGA",
"ACAACGATTATGGACGTTCT",
"ACAGCGACAAGATCCGCTCA",
"TGGACGAGATTCCTCGGACC",
"ATGCCGTGTTCATGCGGCTT",
"TGTTCGTCACTGTACGAATG",
"TCCACGCTGTTATGCGTAGT",
"AGGTCGTGAGCATACGATTG",
"GAAGCGATTGGACTCGCTCC",
"CAAGCGACAGATGTCGCATA",
"TCATCGATTCCATGCGATGA",
"TGCTCGACCTAAGTCGACTT",
"GTTCCGATCTGTTCCGCAGA",
"CCACCGCTGAATTGCGGAAG",
"TGTACGGTAGATAACGCTAG",
"CAGGCGTGTCTTAACGCAGT"
]

# ==============================
# 🧠 STEP 2: LCS FUNCTION
# ==============================

def longest_common_substring(s1, s2):
    s1, s2 = s1.upper(), s2.upper()
    m, n = len(s1), len(s2)
    dp = [[0]*(n+1) for _ in range(m+1)]
    max_len = 0

    for i in range(1, m+1):
        for j in range(1, n+1):
            if s1[i-1] == s2[j-1]:
                dp[i][j] = dp[i-1][j-1] + 1
                if dp[i][j] > max_len:
                    max_len = dp[i][j]

    return max_len

# ==============================
# 🔄 STEP 3: COMPUTE LCS MATRIX
# ==============================

print("Computing LCS matrix...")

lcs_matrix = np.zeros((len(bricks_24), len(bricks_20)))

for i, a in enumerate(bricks_24):
    for j, b in enumerate(bricks_20):
        lcs_matrix[i, j] = longest_common_substring(a, b)

df = pd.DataFrame(lcs_matrix)

print("Done.")

# ==============================
# 📊 STEP 4: HISTOGRAM
# ==============================

lcs_values = df.values.flatten()

plt.figure(figsize=(8, 5))
sns.histplot(lcs_values, bins=30)

plt.title("Histogram of All LCS Values")
plt.xlabel("LCS Length")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

# ==============================
# 📦 STEP 5: BOX PLOT (GROUPED BY 24-nt BRICKS)
# ==============================

# Each row = one 24-nt brick
# So we plot distributions across rows

plt.figure(figsize=(14, 6))
sns.boxplot(data=df.T)  # transpose → each box = one 24-nt brick

plt.title("LCS Distribution per 24-nt Brick")
plt.xlabel("24-nt Brick Index (A)")
plt.ylabel("LCS")

plt.xticks(rotation=90)

plt.tight_layout()
plt.show()

# ==============================
# 📈 STEP 6: OPTIONAL SUMMARY (VERY USEFUL)
# ==============================

print("\nSummary:")
print("Mean LCS:", np.mean(lcs_values))
print("Max LCS:", np.max(lcs_values))
print("Min LCS:", np.min(lcs_values))

# Identify potentially problematic A bricks (high median LCS)
median_lcs = df.median(axis=1)

print("\nTop 10 bricks with highest median LCS:")
print(median_lcs.sort_values(ascending=False).head(10))